# Generated by Django 5.0.7 on 2024-08-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_alter_video_subtopic_alter_video_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
