# Generated by Django 5.0.7 on 2025-05-03 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_remove_video_subtopic_video_subtopics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='topic',
        ),
    ]
