# Generated by Django 5.0.7 on 2024-07-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=50)),
                ('subtopic', models.CharField(blank=True, max_length=50)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
