# Generated by Django 5.0.7 on 2024-08-05 13:21

import django.db.models.deletion
from django.db import transaction
from django.db import migrations, models

BATCH_SIZE = 150

def create_topics_from_video_topics(apps, schema_editor):
    print("Creating topics...")
    Topic = apps.get_model('topics', 'Topic')
    Video = apps.get_model('videos', 'Video')
    
    topic_names = Video.objects.values_list('topic', flat=True).distinct()
    
    for topic_name in topic_names:
        if not Topic.objects.filter(name=topic_name).exists():
            Topic.objects.create(name=topic_name)
            print(f"Created topic: {topic_name}")

def set_video_topic_foreign_keys(apps, schema_editor):
    print("Setting video topic foreign keys...")
    Video = apps.get_model('videos', 'Video')
    Topic = apps.get_model('topics', 'Topic')
    
    total_videos = Video.objects.count()
    print(f"Total videos: {total_videos}")
    
    for start in range(0, total_videos, BATCH_SIZE):
        print(f"Processing batch {start // BATCH_SIZE + 1}...")
        with transaction.atomic():
            videos = Video.objects.all()[start:start + BATCH_SIZE]
            for video in videos:
                topic, created = Topic.objects.get_or_create(name=video.topic)
                video.topic_temp = topic
                video.save()
        print(f"Processed batch {start // BATCH_SIZE + 1}") 
        
class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
        ('videos', '0003_alter_video_description_alter_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="topic_temp",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='videos_temp', to='topics.Topic'),
        ),
        migrations.RunPython(create_topics_from_video_topics),
        migrations.RunPython(set_video_topic_foreign_keys),
        
        migrations.RemoveField(
            model_name="video",
            name="topic",
        ),
        migrations.RenameField(
            model_name="video",
            old_name="topic_temp",
            new_name="topic",
        )
    ]