# Generated by Django 5.0.7 on 2024-08-06 12:32

import django.db.models.deletion
from django.db import migrations, models
from django.db import transaction

BATCH_SIZE = 100
def set_video_subtopic_foreign_keys(apps, schema_editor):
    print("Setting video subtopic foreign keys...")
    Video = apps.get_model('videos', 'Video')
    Subtopic = apps.get_model('topics', 'Subtopic')
    
    total_videos = Video.objects.count()
    print(f"Total videos: {total_videos}")
    for start in range(0, total_videos, BATCH_SIZE):
        print(f"Processing batch {start // BATCH_SIZE + 1}...")
        with transaction.atomic():
            videos = Video.objects.all()[start:start + BATCH_SIZE]
            for video in videos:
                try:
                    subtopic, created = Subtopic.objects.get_or_create(name=video.subtopic, topic=video.topic)
                    if created:
                        print(f"Created subtopic: {subtopic.name} for topic: {subtopic.topic.name}")
                    video.subtopic_temp = subtopic
                    video.save()
                except Exception as e:
                    print(f"Error processing video {video.title}, video ID id {video.id}: {str(e)}")
        print(f"Processed batch {start // BATCH_SIZE + 1}")

class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
        ('videos', '0004_alter_video_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="subtopic_temp",  
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='videos_temp', to='topics.Subtopic'),
        ),
        migrations.RunPython(set_video_subtopic_foreign_keys),
        migrations.RemoveField(
            model_name="video", 
            name="subtopic",
        ),
        migrations.RenameField(
            model_name="video",
            old_name="subtopic_temp",
            new_name="subtopic",
        )
    ]
