# Generated by Django 5.0.7 on 2024-08-15 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
        ('videos', '0005_alter_video_subtopic_alter_video_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='subtopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='topics.subtopic'),
        ),
        migrations.AlterField(
            model_name='video',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='topics.topic'),
        ),
    ]
