# Generated by Django 5.0.7 on 2024-08-15 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_alter_video_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='userLikes',
            field=models.ManyToManyField(blank=True, related_name='liked_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='userSaves',
            field=models.ManyToManyField(blank=True, related_name='saved_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='userViews',
            field=models.ManyToManyField(blank=True, related_name='viewed_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
