# Generated by Django 5.0.7 on 2025-05-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_alter_subtopic_sefaria_text'),
        ('videos', '0008_video_userlikes_video_usersaves_video_userviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='subtopic',
        ),
        migrations.AddField(
            model_name='video',
            name='subtopics',
            field=models.ManyToManyField(related_name='videos', to='topics.subtopic'),
        ),
    ]
