# Generated by Django 5.0.7 on 2025-05-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='sefaria_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
